export const sel = {
  toast: '[data-sonner-toast]',
  alertDialog: '[role="alertdialog"]',
  dialog: '[role="dialog"]',
  submit: 'form button[type="submit"]',
  nameInput: 'input[name="name"]',
  summaryInput: 'textarea[name="summary"]',
  titleInput: 'input[name="title"]',
  descriptionInput: 'textarea[name="description"]',
  questionInput: 'input[placeholder="Type your question here..."]',
  emailInput: 'input[name="email"]',
  passwordInput: 'input[name="password"]',
  fullName: 'form#profile-form input[name="fullName"]',
  bio: 'textarea[name="bio"]',
  profileSubmit: 'form#profile-form button[type="submit"]',
  currentPassword: 'input[name="currentPassword"]',
  confirmPassword: 'input[name="confirmPassword"]',
  passwordSubmit: 'form#password-form button[type="submit"]',
  deleteButton: 'button[data-variant="destructive"]:has(svg.lucide-trash-2)',
  confirmation: 'input[name="confirmation"]',
  projectSettingsName: 'form#project-settings-form input[name="name"]',
  projectSettingsSubmit: 'form#project-settings-form button[type="submit"]',
} as const;

export const E2E_PASSWORD = 'E2eTestPass1!';
